alter table public.customers
add column if not exists municipal text,
add column if not exists honesty text,
add column if not exists id_number text,
add column if not exists nationality text,
add column if not exists sex text,
add column if not exists occupation text,
add column if not exists health_cert_number text,
add column if not exists health_cert_expiry text,
add column if not exists health_cert_issue_hijri text,
add column if not exists health_cert_issue_gregorian text,
add column if not exists edu_program_end text,
add column if not exists edu_program_type text,
add column if not exists facility_name text,
add column if not exists license_number text,
add column if not exists facility_number text;
